import { Professional, Trade } from '@/types';

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: '1',
    name: 'Carlos Silva',
    trade: [Trade.PEDREIRO, Trade.PINTOR],
    location: 'São Paulo, SP',
    avatar: 'https://picsum.photos/seed/carlos/200/200',
    bio: 'Especialista em alvenaria e acabamentos com mais de 15 anos de experiência. Foco em reformas residenciais rápidas e limpas.',
    yearsExperience: 15,
    verified: true,
    hourlyRate: 'R$ 100',
    hourlyRateValue: 100,
    availability: 'Disponível',
    certifications: ['Técnico em Edificações - SENAI', 'NR-35 Trabalho em Altura'],
    portfolio: [
      'https://picsum.photos/seed/obra1/400/300',
      'https://picsum.photos/seed/obra2/400/300',
      'https://picsum.photos/seed/obra3/400/300',
    ],
    reviews: [
      { id: 'r1', author: 'Ana Souza', rating: 5, text: 'O Carlos é excelente! Fez o reboco da minha sala super rápido e deixou tudo limpo.', date: '2023-10-15' },
      { id: 'r2', author: 'Roberto Dias', rating: 4, text: 'Bom profissional, chegou no horário. O preço foi justo.', date: '2023-11-02' },
      { id: 'r3', author: 'Fernanda Lima', rating: 5, text: 'Muito honesto e caprichoso. Recomendo de olhos fechados.', date: '2023-12-10' },
    ],
  },
  {
    id: '2',
    name: 'Mariana Costa',
    trade: [Trade.ARQUITETO],
    location: 'Rio de Janeiro, RJ',
    avatar: 'https://picsum.photos/seed/mariana/200/200',
    bio: 'Arquiteta focada em projetos de interiores sustentáveis e otimização de pequenos espaços.',
    yearsExperience: 8,
    verified: true,
    hourlyRate: 'R$ 300',
    hourlyRateValue: 300,
    availability: 'Consulte',
    certifications: ['CAU Ativo', 'Mestrado em Sustentabilidade'],
    portfolio: [
      'https://picsum.photos/seed/arq1/400/300',
      'https://picsum.photos/seed/arq2/400/300',
    ],
    reviews: [
      { id: 'r4', author: 'Lucas Mendes', rating: 5, text: 'A consultoria da Mariana mudou meu apartamento. Ideias geniais!', date: '2024-01-20' },
    ],
  },
  {
    id: '3',
    name: 'João Pedro',
    trade: [Trade.ENCANADOR, Trade.ELETRICISTA],
    location: 'Belo Horizonte, MG',
    avatar: 'https://picsum.photos/seed/joao/200/200',
    bio: 'Soluções hidráulicas de emergência e instalações prediais. Atendimento 24h.',
    yearsExperience: 10,
    verified: true,
    hourlyRate: 'R$ 120',
    hourlyRateValue: 120,
    availability: 'Disponível',
    certifications: ['Instalador Hidráulico Amanco'],
    portfolio: [
      'https://picsum.photos/seed/encan1/400/300',
      'https://picsum.photos/seed/encan2/400/300',
    ],
    reviews: [
      { id: 'r5', author: 'Carla Nunes', rating: 3, text: 'Resolveu o problema, mas demorou um pouco para chegar.', date: '2023-09-05' },
      { id: 'r6', author: 'Paulo Viera', rating: 5, text: 'Salvou minha cozinha no domingo a noite. Profissional nota 10.', date: '2023-12-15' },
    ],
  },
  {
    id: '4',
    name: 'Roberto Almeida',
    trade: [Trade.ELETRICISTA],
    location: 'São Paulo, SP',
    avatar: 'https://picsum.photos/seed/roberto/200/200',
    bio: 'Instalações elétricas, quadros de distribuição e automação residencial. Credenciado pelo CREA.',
    yearsExperience: 12,
    verified: true,
    hourlyRate: 'R$ 110',
    hourlyRateValue: 110,
    availability: 'Agenda Cheia',
    certifications: ['CREA-SP', 'NR-10 Segurança em Instalações Elétricas'],
    portfolio: [
      'https://picsum.photos/seed/eletri1/400/300',
    ],
    reviews: [
      { id: 'r7', author: 'Empresa X', rating: 5, text: 'Serviço técnico impecável.', date: '2024-02-01' },
    ],
  },
  {
    id: '5',
    name: 'Julia Ramos',
    trade: [Trade.PINTOR],
    location: 'Curitiba, PR',
    avatar: 'https://picsum.photos/seed/julia/200/200',
    bio: 'Pintura decorativa, texturas e restauração de paredes. Acabamento fino.',
    yearsExperience: 5,
    verified: false,
    hourlyRate: 'R$ 75',
    hourlyRateValue: 75,
    availability: 'Disponível',
    certifications: [],
    portfolio: [
      'https://picsum.photos/seed/pint1/400/300',
      'https://picsum.photos/seed/pint2/400/300',
      'https://picsum.photos/seed/pint3/400/300',
    ],
    reviews: [],
  },
];
